version: '3'

services:
  webserver1:
    build:
      context: ./webserver1
      restart: always
    ports:
      - "5001:5001"
    

  webserver2:
    build:
      context: ./webserver2 
      restart: always  
    ports:
      - "5002:5002"  

  portainer:
    image: portainer/portainer
    container_name: portainer
    restart: always
    ports:
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data   

adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - "8080:8080" 

prometheus:
    image: prom/prometheus
    container_name: prometheus
    restart: always
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus:/etc/prometheus

grafana:
    image: grafana/grafana
    container_name: grafana
    restart: always
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_SECURITY_ALLOW_EMBEDDING=true
    depends_on:
      - prometheus 

networks:
  postgres:
    driver: bridge 

volumes:
  portainer_data:
